services:
  backend:
    build: ./server_backend/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./server_backend/.env
    # Add dependency on a local mongodb if needed, otherwise uses the one in .env
    # depends_on:
    #   - mongodb

  frontend:
    build: ./client_frontend/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

# networks:
#   default:
#     name: agri-intelligence-network
