services:
  # Backend Service
  - type: web
    name: agri-backend
    runtime: docker
    dockerContext: ./server_backend
    dockerfilePath: server_backend/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: ALLOWED_ORIGINS
        value: "https://agri-frontend-uwdc.onrender.com"

  # Frontend Service
  - type: web
    name: agri-frontend
    runtime: docker
    dockerContext: ./client_frontend
    dockerfilePath: client_frontend/Dockerfile
    plan: free
    envVars:
      - key: VITE_API_URL
        value: "https://agri-backend-qyjz.onrender.com"